export enum Role {
  USUARIO_READ = "USUARIO_READ",
  USUARIO_WRITE = "USUARIO_WRITE",
  USUARIO_DELETE = "USUARIO_DELETE",
  GRUPO_READ = "GRUPO_READ",
  GRUPO_WRITE = "GRUPO_WRITE",
  GRUPO_DELETE = "GRUPO_DELETE",
}
